function rounded_data = round_to_three(data)
    rounded_data = arrayfun(@(x) ...
        (isnan(x) || x == 0) * x + ...
        (~isnan(x) && x ~= 0) * round(x, max(0, min(10, floor(3 - log10(abs(x)))))), data);
end
